//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public string CitaID { get; set; }
        public string ClienteID { get; set; }
        public string PlacaNumero { get; set; }
        public System.DateTime FechaCita { get; set; }
        public string SucursalID { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Sucursales Sucursales { get; set; }
    }
}
